# --- itchybarn.com ---

server {
    listen 80;
    server_name dev.itchybarn.com;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://dev.itchybarn.com$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name dev.itchybarn.com;

    ssl_certificate /etc/letsencrypt/live/itchybarn.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/itchybarn.com/privkey.pem;

    root /home/ec2-user/portfolio/frontend/dist; # tells nginx where to look for files
    index index.html; # it's convention to have this, but is essentially the same as /index.html down in try_files

    location / {
        try_files $uri $uri/ /index.html;
        # uri is the Uniform Resource Identifier. it first looks for a direct file path, then a directory, and finally serves the default index.html
        # if i pass in /about, for example, it will check for a direct file first, before eventually sending me to the index.html, where react router can pick up the /about.
    }

    location /api/ { # goes directly to Flask
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

